config/routes.rb
Rails.application.routes.draw do

	# Settlemets
	get 'settlements/fetch_settlements/:contract_id', to: 'settlements#fetch_settlements', as: 'fetch_settlements'
	get 'settlement/settlement_pdf/:id', to: 'settlements#settlement_pdf', as: 'settlement_pdf'
	get 'settlements/new/:contract_id', to: 'settlements#new', as: 'new_settlement'
	resources :settlements, except: [:new, :show, :destroy]

	# Payments
	resources :payments, except: [:new, :show]
	get 'payments/show_proprietary_payment/:administration_number', to: 'payments#show_proprietary_payment', as: 'show_proprietary_payment'
	get 'payments/:administration_number/generate_warranty_receipt', to: 'payments#generate_warranty_receipt', as: 'generate_warranty_receipt'
	get 'payments/new/:administration_number', to: 'payments#new', as: 'new_payment'
	get 'payments/new/update_discounts/:administration_number/:month', to: 'payments#update_discounts', as: 'payments_update_discounts'
	get 'payments/new/update_ipc/:year/:month', to: 'payments#update_ipc', as: 'payments_update_ipc'
	get 'payments/new/:payment_id/generate_receipt', to: 'payments#generate_payment_receipt', as: 'generate_payment_receipt'
	get 'payments/new/warranty/:administration_number', to: 'payments#new_warranty', as: 'new_warranty_payment'

	# Contracts
	post  'contracts/assign_admin_n', to: 'contracts#assign_admin_n', as: 'assign_admin_n'
	get   'contracts/update_readjustment_fields', to: 'contracts#update_readjustment_fields'
	get   'contracts/:id/show_terminate_form', to: 'contracts#show_terminate_form', as: 'show_termiante_form'
	get   'contracts/:id/show_terminate_form/add_expense/:count', to: 'contracts#add_contract_expense', as: 'add_contract_expense'
	get   'contracts/:id/show_warranty_receipt', to: 'contracts#show_warranty_receipt', as: 'contracts_show_warranty_receipt'
	patch 'contracts/:id/terminate', to: 'contracts#terminate', as: 'terminate_contract'
	get   'contracts/:id/show', to: 'contracts#show', as: 'show_contract'
	get   'contracts/show/discharge/:discharge_id', to: 'contracts#show_discharge', as: 'show_contract_discharge'
	get   'contracts/show/inventory/:inventory_id', to: 'contracts#show_inventory', as: 'show_contract_inventory'
	resources :contracts, except: [:show]

	# Expenses
	get 'expenses/fetch/:property_id', to: 'expenses#fetch_expenses', as: 'fetch_expenses'
	get 'expenses/new/:property_id', to: 'expenses#new', as: 'new_expense'
	get 'expenses/fetch_expense/:id', to: 'expenses#fetch_expense'
	resources :expenses, except: [:new, :show]

	# Associated Documents
	resources :associated_documents

	# Notifications
	resources :notifications

	# Properties
	resources :properties, except: [:show]
	get 'properties/new/:user_id', to: 'properties#new_property'
	get 'properties/new/:user_id/add_administration_beneficiary/:count', to: 'properties#add_administration_beneficiary', as: 'add_administration_beneficiary'
	get 'properties/create_administration_number', to: 'properties#create_administration_number', as: 'create_administration_number'
	get 'properties/assign_administration_number/:admin_n', to: 'properties#assign_administration_number', as: 'assign_administration_number'
	get 'properties/delete/:id', to: 'properties#delete', as: 'delete_property'
	get 'properties/show_mandate/:id', to: 'properties#show_mandate', as: 'show_property_mandate'

	# USERS
	get  'users/delete/:id', to: 'users#delete', as: 'delete_user'
	# Proprietaries
	get  'users/proprietaries', to: 'users#proprietaries'
	get  'users/new/proprietary', to: 'users#new_proprietary'
	get  'users/fetch_properties/:user_id', to: 'users#fetch_properties'
	get  'users/fetch_settlements/:user_id', to: 'users#fetch_settlements'
	post 'users/proprietaries', to: 'users#create_proprietary', as: 'create_proprietary'
	# Tenants
	get  'users/tenants', to: 'users#tenants'
	get  'users/new/tenant', to: 'users#new_tenant'
	get  'users/new/tenant/:administration_number', to: 'users#new_tenant', as: 'create_tenant_with_admin_n'
	post 'users/tenants', to: 'users#create_tenant', as: 'create_tenant'
	get  'users/tenant/:user_id/fetch/payments', to: 'users#fetch_tenant_payments', as: 'fetch_tenant_payments'
	get  'users/tenant/show/payment/receipt/:payment_id', to: 'users#show_tenant_payment_receipt', as: 'show_tenant_payment_receipt'
	get  'users/tenant/show/contract/:contract_id', to: 'users#show_tenant_contract', as: 'show_tenant_contract'
	get  'users/tenant/terminate_contract/:contract_id', to: 'users#show_tenant_terminate_contract_form', as: 'show_tenant_terminate_contract_form'
	resources :users, except: [:index, :show, :new]

	# Administration Numbers
	get 'administration/index', to: 'administration_numbers#index', as: 'administration_numbers'

	# Reports
	get 'reports/collection', to: 'reports#collection', as: 'reports_collection'
	get 'reports/collection_debts/:admin_number', to: 'reports#collection_debts', as: 'reports_collection_debts'
	get 'reports/collection_debts/:admin_number/generate.pdf', to: 'reports#collection_debts', as: 'reports_collection_debts_pdf'
	get 'reports/settlements', to: 'reports#settlements', as: 'reports_settlements'
	get 'reports/property_return', to: 'reports#property_return', as: 'reports_property_return'
	get 'reports/active_administrations', to: 'reports#active_administrations', as: 'reports_active_administrations'
	get 'reports/contributions', to: 'reports#contributions', as: 'reports_contributions'
	get 'reports/expenses', to: 'reports#expenses', as: 'reports_expenses'
	get 'reports/administration_profit', to: 'reports#administration_profit', as: 'reports_administration_profit'
	get 'reports/property_works', to: 'reports#property_works', as: 'reports_property_works'
	get 'reports/unpaid_settlements', to: 'reports#unpaid_settlements', as: 'reports_unpaid_settlements'

	# Property Works
	get   'property_works', to: 'property_works#index', as: 'property_works'
	get   'property_works/show/:property_id', to: 'property_works#show', as: 'show_property_works'
	get   'property_works/new/:property_id', to: 'property_works#new', as: 'new_property_work'
	get   'property_works/new/add_expense/:count', to: 'property_works#add_expense', as: 'property_work_add_expense'
	post  'property_works', to: 'property_works#create'
	patch 'property_works/:id', to: 'property_works#update', as: 'update_property_work'

	# System Control
	get   'system_controls/info', to: 'system_controls#info', as: 'system_info'
	patch 'system_controls/update_info', to: 'system_controls#update_info', as: 'system_update_info'
	get   'system_controls/users', to: 'system_controls#users', as: 'system_users'
	post  'system_controls/users', to: 'system_controls#create_user', as: 'system_create_user'
	get   'system_controls/users/edit/:user_id', to: 'system_controls#edit_user', as: 'system_edit_user'
	patch 'system_controls/users/:user_id', to: 'system_controls#update_user', as: 'system_update_user'
	get   'system_controls/users/deactivate/:user_id', to: 'system_controls#deactivate_user', as: 'system_deactivate_user'
	get   'system_controls/users/activate/:user_id', to: 'system_controls#activate_user', as: 'system_activate_user'
	get   'system_controls/logs', to: 'system_controls#logs', as: 'system_logs'

	# Search
	post 'search', to: 'search#search', as: 'search'

	# Sessions
	resources :sessions, only: [:create, :destroy]
	get  'signup', to: 'users#new', as: 'signup'
	get  'login',  to: 'sessions#new', as: 'login'
	get  'logout', to: 'sessions#destroy', as: 'logout'
	get  'forgot_password', to: 'sessions#forgot_password', as: 'forgot_password'
	post 'restore_password', to: 'sessions#restore_password', as: 'restore_password'


	# Home and login
	get 'home/index', as: 'home'

	# Root definition
	root 'home#index'
end

app/models/settlement.rb
class Settlement < ActiveRecord::Base

	belongs_to :contract

	validates_presence_of :contract_id, :month, :year, :invoice_number

	include Month

	# File handling
	has_one_attached :invoice
	has_one_attached :transference
	has_one_attached :receipt
	include FileValidation
	validate {
		file_validation(:invoice)
		file_validation(:transference)
		file_validation(:receipt)
	}

	after_rollback {
		file_delete(:invoice)
		file_delete(:transference)
		file_delete(:receipt)
	}

	def amount_to_transfer
		# Start the amount by the neat rent
		amount = self.contract.rent

		# Search expenses for this settlement that were not made by the
		# proprietary
		#expenses = Expense
		#	.where(property_id: self.contract.administration_number.property.id)
		#	.where('extract(year from date) = ?', self.year)
		#	.where('extract(month from date) = ?', Settlement.months[self.month])
		#	.where(proprietary: false)

		# Substract all of those expenses from the rent
		#expenses.map{ |e| amount -= e.amount }

		amount -= self.discount

		return amount
	end

	def discount
		discount = 0
		# Search expenses for this settlement that were not made by the
		# proprietary
		propertyHasExpenses = PropertyHasExpense
			.where(property_id: self.contract.administration_number.property.id)

		expense_amounts = propertyHasExpenses.map do |phe|
			if phe.expense.date.year == self.year and
			   phe.expense.date.month == Settlement.months[self.month] and
			   phe.expense.proprietary == false
				phe.expense.amount
			else
				0
			end
		end

		# Calcuate discuount by adding the amount of expenses payed by the tenant
		expense_amounts.each do |ea|
			discount += ea
		end

		return discount
	end

	def invoice_path
		ActiveStorage::Blob.service.send(:path_for, self.invoice.key)
	end

	# Returs string with the range covered by the settlement
	def range
		date1 = Date.new(self.year, self.month_number, self.contract.start_date.day)
		date2 = date1 + 1.month

		"#{date1.strftime('%d-%m-%Y')} hasta #{date2.strftime('%d-%m-%Y')}"
	end

	def generate_receipt_pdf(params = {})
		pdf_string = WickedPdf.new.pdf_from_string(
			#ActionController::Base.new().render_to_string(
			ApplicationController.new.render_to_string(
				:template => 'settlements/settlement_pdf_template',
				:locals => {
					:settlement => self,
					:contract => self.contract,
					:proprietary => self.contract.administration_number.proprietary,
					:tenant => self.contract.administration_number.tenant,
					:property => self.contract.administration_number.property,
					:admin_n => self.contract.administration_number,
				},
				:layout => 'receipt',
			),

			#:pdf => estimate_number,
			:layout => false,
			:page_size => 'Letter',
			:lowquality => false,
			:handlers => [:erb],
			:formats => [:html],
			#:margin => {:top                => 5,
			#			:bottom             => 0,
			#			:left               => 0,
			#			:right              => 0},
			:orientation => 'Portrait',
			:disposition => 'attachment'
		)

		tempfile = Tempfile.new(["temp", ".pdf"], Rails.root.join('tmp'))
		tempfile.binmode
		tempfile.write pdf_string
		tempfile.close

		self.receipt.attach(io: File.open(tempfile.path), filename: 'liquidacion.pdf' )

		tempfile.unlink
	end

end

app/controllers/settlements_controller.rb
class SettlementsController < ApplicationController
	before_action only:   [:index, :fetch_settlement, :fetch_settlements] do authorize_read(Settlement) end
	before_action except: [:index, :fetch_settlement, :fetch_settlements] do authorize_manage(Settlement) end

	def index
		@admin_numbers = AdministrationNumber.active_contract
	end

	def new
		# Query last settlement generated
		last_settlement = Settlement
			.where(contract_id: params[:contract_id])
			.order(:year)
			.order(:month)
			.last

		# Calculate next month and year
		if last_settlement.nil?
			contract_start_date = Contract.find(params[:contract_id]).start_date
			next_settlement_year = contract_start_date.year
			next_settlement_month = contract_start_date.month
			@settlement_number = 1
		else
			next_settlement_year = last_settlement.year
			next_settlement_month = last_settlement.month_number + 1
			@settlement_number = Settlement.where(contract_id: params[:contract_id]).count + 1
		end
		if next_settlement_month > 12
			next_settlement_month = 1
			next_settlement_year += 1
		end
		@settlement = Settlement.new(contract_id: params[:contract_id], year: next_settlement_year, month: next_settlement_month, date: Date.today, number: @settlement_number)
		@expenses = get_expenses(@settlement.contract.administration_number.property.id, next_settlement_year, next_settlement_month)
		calculate_totals

	end

	#def edit
	#	@settlement = Settlement.find(params[:id])
	#	@expenses = get_expenses(@settlement.contract.property.id, @settlement.year, Settlement.months[@settlement.month])
	#	@remaining_months_collection = get_remaining_month_collection(@settlement.contract_id, @settlement.year)
	#	calculate_totals
    #
	#	render 'new'
	#end

	def create
		# Create new settlement with provided params
		@settlement = Settlement.new(settlement_params)
		puts @settlement.inspect

		# Save and render settlements or form errors
		@settlement.generate_receipt_pdf
		@settlement.contract.generate_proprietary_payment_pdf(nil, @settlement)
		if @settlement.save
			LogEntry.create user: current_user, datetime: DateTime.now, action: 'creó', model: 'liquidación', description: "N ADM #{@settlement.contract.administration_number.id}"
			@settlements = Settlement.where(contract_id: params[:settlement][:contract_id])
			render 'fetch_settlements'
		else
			@expenses = get_expenses(@settlement.contract.administration_number.property.id, @settlement.year, @settlement.month_number)
			calculate_totals
			render 'new'
		end
	end

	#def update
	#	# Fetch current settlement
	#	@settlement = Settlement.find(params[:id])
    #
	#	# Update and render settlements or form errors
	#	if @settlement.update(settlement_params)
	#		@settlements = Settlement.where(contract_id: params[:settlement][:contract_id])
	#		render 'fetch_settlements'
	#	else
	#		@remaining_months_collection = get_remaining_month_collection(@settlement.contract_id, @settlement.year)
	#		@expenses = get_expenses(@settlement.contract.property.id, @settlement.year, Settlement.months[@settlement.month])
	#		calculate_totals
	#		render 'new'
	#	end
	#end

	# AJAX APIs
	# Fetches settlements made for a property
	def fetch_settlements
		@settlements = Settlement.where(contract_id: params[:contract_id])
		puts @settlements.inspect
	end

	# Updates months that dont yet have a settlement for a given year
	#def update_form_months
	#	@settlement = Settlement.new(contract_id: params[:contract_id], year: params[:settlement][:year])
	#	@remaining_months_collection = get_remaining_month_collection(params[:contract_id], params[:settlement][:year])
	#	current_month = Settlement.months[@remaining_months_collection.values[0]]
	#	@expenses = get_expenses(@settlement.contract.property.id, params[:settlement][:year], current_month)
	#	calculate_totals
    #
	#	render 'update_form_months'
	#end

	# Updates the expenses in the form
	#def update_form_expenses
	#	@settlement = Settlement.new(contract_id: params[:contract_id])
	#	month = Settlement.months[params[:settlement][:month]]
	#	@expenses = get_expenses(@settlement.contract.property.id, params[:year], month)
	#	calculate_totals
    #
	#	render 'update_form_expenses'
	#end

	# Searches a particular settlement and shows invoice
	def fetch_settlement
		@settlement = Settlement.find(params[:id])
	end

	def settlement_pdf
		@settlement = Settlement.find(params[:id])
		#@settlement.generate_receipt_pdf
		#@settlement.save
	end


	private

		def settlement_params
			params
				.require(:settlement)
				.permit(
					:contract_id, :month, :year, :transference, :invoice,
					:invoice_number, :date, :number
				)
		end

		#def get_remaining_month_collection(contract_id, year)
		#	current_settlements = Settlement.where(contract_id: contract_id, year: year)
		#	settled_months = current_settlements.pluck(:month).map{|m| m.to_sym}
		#	remaining_months = Settlement::MONTH_TO_STR.except(*settled_months)
		#	remaining_months.invert
		#end

		def get_expenses(property_id, year, month)
			expenses = []

			expenses += Expense
				.joins(:property_has_expense)
				.where(expenses: {proprietary: true})
				.where(property_has_expenses: {property_id: property_id})
				.where('extract(year from date) = ?', year)
				.where('extract(month from date) = ?', month)

			expenses += Expense
				.joins(property_work_has_expense: :property_work)
				.where(expenses: {proprietary: true})
				.where(property_works: {property_id: property_id})
				.where('extract(year from date) = ?', year)
				.where('extract(month from date) = ?', month)

			return expenses
		end

		def calculate_totals
			@total_discount = 0
			@expenses.each{ |e| @total_discount += e.amount }
			@amount_to_transfer = @settlement.contract.rent - @total_discount
		end
end

app/helpers/settlements_helper.rb
module SettlementsHelper
end

app/views/settlements/_form.html.erb
<%= simple_form_for @settlement, remote: true do |f| %>
	<div class="row">
		<!-- Settlement info -->
		<div class="col-sm-6">
			<div class="row">
				<div class="col-sm-6"><%= label_tag		   :admin_n, 'N° de Administración', class: 'control-label' %></div>
				<div class="col-sm-6"><%= number_field_tag :admin_n, @settlement.contract.administration_number.id, class: 'form-control', disabled: true %></div>
			</div>

			<div class="row">
				<div class="col-sm-6"><%= label_tag :number, 'N° de Liquidación', class: 'control-label' %></div>
				<div class="col-sm-6"><%= f.input   :number, label: false, class: 'form-control', readonly: true %></div>
			</div>

			<div class="row">
				<div class="col-sm-6"><%= label_tag :date, 'Fecha', class: 'control-label' %></div>
				<div class="col-sm-6"><%= f.input	:date, as: :date_picker, label: false, class: 'form-control'%></div>
			</div>

			<div class="row">
				<div class="col-sm-6"><%= label_tag		   :rent, 'Monto Arriendo', class: 'control-label' %></div>
				<div class="col-sm-6"><%= text_field_tag :rent, fmt_number(@settlement.contract.rent), class: 'form-control', disabled: true %></div>
			</div>

			<div class="row">
				<div class="col-sm-6"><%= label_tag		 :settlement_range, 'Mes de Arriendo', class: 'control-label' %></div>
				<div class="col-sm-6"><%= text_field_tag :settlement_range, @settlement.range, class: 'form-control', disabled: true %></div>
			</div>

			<div class="row">
				<div class="col-sm-6"><%= label_tag		   :amount_of_readjustments, 'Reajustes', class: 'control-label' %></div>
				<div class="col-sm-6"><%= number_field_tag :amount_of_readjustments, @settlement.contract.amount_of_readjustments, class: 'form-control', disabled: true %></div>
			</div>

			<div class="row">
				<div class="col-sm-6"><%= label_tag		   :delay_penalties, 'Multas por Atraso', class: 'control-label' %></div>
				<div class="col-sm-6"><%= text_field_tag :delay_penalties, 0, type: 'text', class: 'form-control float-field' %></div>
			</div>

			<div class="row">
				<div class="col-sm-6"><%= label_tag		 :admin_percentage, "% de Administración (#{fmt_number @settlement.contract.administration_number.property.adm_percentage}%)", class: 'control-label' %></div>
				<div class="col-sm-6"><%= text_field_tag :admin_percentage, fmt_number(@settlement.contract.administration_percentage), class: 'form-control', disabled: true %></div>
			</div>

			<div class="row">
				<div class="col-sm-6"><%= label_tag :invoice_number, 'N° de Factura', class: 'control-label' %></div>
				<div class="col-sm-6"><%= f.input	:invoice_number, label: false, class: 'form-control'%></div>
			</div>

			<div class="row">
				<div class="col-sm-6"><%= label_tag		   :total_discount, 'Total Descuentos (Gastos y Pagos)', class: 'control-label' %></div>
				<div class="col-sm-6"><%= text_field_tag :total_discount, fmt_number(@total_discount), class: 'form-control', disabled: true %></div>
			</div>

			<div class="row">
				<div class="col-sm-6"><%= label_tag		   :transference_total, 'Transferencia a Cta. Cte', class: 'control-label' %></div>
				<div class="col-sm-6"><%= text_field_tag :transference_total, fmt_number(@settlement.contract.rent - @total_discount - @settlement.contract.administration_percentage), class: 'form-control', disabled: true %></div>
			</div>
		</div>

		<!-- Discounts info -->
		<div class="col-sm-6">
			<table class="table table-bordered" style="margin: auto;">
				<thead class="thead-dark">
					<tr class="text-center">
						<th colspan="2">Descuentos</th>
					</tr>
				</thead>
				<tbody>
					<% @expenses.each do |expense| %>
						<tr class="text-center">
							<td><%= expense.description %></td>
							<td><%= fmt_number expense.amount %></td>
						</tr>
					<% end %>
				</tbody>
			</table>

			<span style="float: right;"><strong>Total: <%= fmt_number @total_discount%></strong></span>
		</div>
	</div>

	<br/>
	<!-- Buttons -->
	<div class="row">
		<!-- File buttons -->
		<div class="col-sm-6">
			<div class="row">
				<div class="col-sm-6">
					<%= render 'partials/file_button', f: f, file_field: :transference, label: 'Subir Comprobante Transferencia', previous: true %>
				</div>
				<div class="col-sm-6">
					<%= render 'partials/file_button', f: f, file_field: :invoice, label: 'Subir Factura', previous: true %>
				</div>
			</div>
		</div>

		<!-- Submit buttons -->
		<div class="col-sm-6">
			<%= f.submit 'Generar', class: 'btn btn-success mt-1', id: 'submit-button', onclick: 'modal.showProcessing();' %>
			<button class="btn btn-danger mt-1 pull-right" data-dismiss="modal">Cancelar</button>
		</div>
	</div>

	<%= f.input :contract_id, as: :hidden %>
	<%= f.input :year, as: :hidden %>
	<%= f.input :month, as: :hidden, input_html: {value: @settlement.month.to_sym} %>
<% end %>

<%= content_for :extra_js do %>
	helpers.setFloatFieldListenerByClass('float-field');
<% end %>
<script>
	if (typeof helpers != 'undefined') {
		helpers.setFloatFieldListenerByClass('float-field');
	}
</script>

app/views/settlements/_settlement_pdf.html.erb
<!--<div class="row">
	<div class="col-sm-12">
		<iframe id="pdf-frame" title="" width="100%" height="100%" src="<%= url_for(@settlement.receipt) %>"></iframe>

		<button class="btn btn-danger btn-lg mr-4", onclick="helpers.printFrame('pdf-frame');">Imprimir</button>
		<button class="btn btn-danger btn-lg mr-4", onclick="modal.hide();">Cancelar</button>
	</div>
</div> -->

<iframe id="pdf-frame" title="" width="100%" style="min-height: 400px;"src="<%= url_for(@settlement.receipt) %>"></iframe>

<button class="btn btn-danger btn-lg mr-4", onclick="helpers.printFrame('pdf-frame');">Imprimir</button>
<button class="btn btn-danger btn-lg mr-4", onclick="modal.hide();">Cancelar</button>

app/views/settlements/_table.html.erb
<table class="table table-bordered table-responsive">
	<thead class="thead-dark" style="width: 100%">
		<tr class="text-center">
			<th>N Liq</th>
			<th>Fecha</th>
			<th>Mes Arriendo</th>
			<th>Reajustes</th>
			<th>Multas por Atraso</th>
			<th>% Adm</th>
			<th>N Factura</th>
			<th>Total Descuento</th>
			<th>Transf. Cta. Cte.</th>
			<th>Accion</th>
		</tr>
	</thead>


	<tbody id="show_settlements_tbody">
		<% @settlements.each do |settlement| %>
			<tr class="text-center">
				<td class="cell-tght"><%= settlement.id %></td>
				<td class="cell-tght"><%= settlement.created_at.strftime("%d-%m-%Y") %></td>
				<td class="cell-tght"><%= settlement.month_string %></td>
				<td class="cell-tght"><%= settlement.contract.amount_of_readjustments %></td>
				<td class="cell-tght"> ? </td>
				<td class="cell-tght"><%= fmt_number settlement.contract.administration_percentage %></td>
				<td class="cell-tght"><%= settlement.invoice_number %></td>
				<% settlement_discount = settlement.discount %>
				<td class="cell-tight"><%= fmt_number(settlement_discount) %></td>
				<td class="cell-tight"><%= fmt_number(settlement.contract.rent - settlement_discount - settlement.contract.administration_percentage) %></td>
				<td class="cell-tight p-0">
					<%= link_to 'Ver PDF', settlement_pdf_path(settlement.id), class: 'btn btn-danger', remote: true %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<div class="d-flex w-100 justify-content-end mt-5 mb-3">
	<button class="btn btn-info mr-2" data-dismiss="modal">Cerrar</button>
</div>

<style>
	.cell-tight{
		padding: 2px !important;
	}

	.table-tight{
		font-size: 12px;
	}
</style>

app/views/settlements/_table_admin_n.html.erb
<table class="table  table-bordered table-responsive-sm">
	<thead class="thead-dark">
		<tr class="text-center">
			<th>N ADM</th>
			<th>Propietario</th>
			<th>Direccion</th>
			<th>Estado</th>
			<th>Acciones</th>
		</tr>
	</thead>
	<tbody>
		<% admin_numbers.each do |n| %>
			<tr class="text-center">
				<td><%= n.id %></td>
				<td><%= n.proprietary.name %></td>
				<td><%= n.property.address %></td>
				<td><%= n.property.state_string %></td>
				<td>
					<%= link_to "Crear liquidacion", new_settlement_path(n.contract.id), remote: true, class: 'btn btn-info mt-1' %>
					<%= link_to "Ver Liquidaciones", fetch_settlements_path(n.contract.id), remote: true, class: 'btn btn-success mt-1' %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/settlements/_update_form_months.html.erb
<%= simple_form_for @settlement do |f| %>
	<%= f.input :month, collection: @remaining_months_collection, include_blank: false, input_html: { data: {remote: :true, url: "/settlements/update_form_expenses/#{@settlement.contract.property.id}/#{@settlement.year}"} } %>
<% end %>

app/views/settlements/create.js.erb
modal.configDelete();
modal.reset();
modal.setBody('Los datos se han guardado exitosamente');
modal.show();

app/views/settlements/fetch_settlements.js.erb
modal.reset();
modal.configXl();
modal.setHeader('LIQUIDACIONES');
modal.setBody(  "<%= j render 'table' %>");
modal.show();

app/views/settlements/new.js.erb
modal.reset();
modal.configXl();
modal.setHeader('Generar Liquidación Propietario');
modal.setBody("<%= j render 'form', contract: @contract %>" );
modal.show();

app/views/settlements/settlement_pdf.js.erb
modal.reset();
modal.configXl();
modal.setBody("<%= j render 'settlement_pdf' %>");
modal.show();

app/views/settlements/update_form_expenses.js.erb
$('#expenses').replaceWith('<%= j render "form_expenses", expenses: @expenses %>');
$('#totals').replaceWith('<%= j render "form_totals", total_discount: @total_discount, amount_to_transfer: @amount_to_transfer %>');

app/views/settlements/update_form_months.js.erb
updatedMonths = $('#settlement_month', $('<%= j render "update_form_months", contract: @contract %>'));
$('#settlement_month').replaceWith(updatedMonths);

$('#expenses').replaceWith('<%= j render "form_expenses", expenses: @expenses %>');
$('#totals').replaceWith('<%= j render "form_totals", total_discount: @total_discount, amount_to_transfer: @amount_to_transfer %>');