config/routes.rb
Rails.application.routes.draw do

	# Settlemets
	get 'settlements/fetch_settlements/:contract_id', to: 'settlements#fetch_settlements', as: 'fetch_settlements'
	get 'settlement/settlement_pdf/:id', to: 'settlements#settlement_pdf', as: 'settlement_pdf'
	get 'settlements/new/:contract_id', to: 'settlements#new', as: 'new_settlement'
	resources :settlements, except: [:new, :show, :destroy]

	# Payments
	resources :payments, except: [:new, :show]
	get 'payments/show_proprietary_payment/:administration_number', to: 'payments#show_proprietary_payment', as: 'show_proprietary_payment'
	get 'payments/:administration_number/generate_warranty_receipt', to: 'payments#generate_warranty_receipt', as: 'generate_warranty_receipt'
	get 'payments/new/:administration_number', to: 'payments#new', as: 'new_payment'
	get 'payments/new/update_discounts/:administration_number/:month', to: 'payments#update_discounts', as: 'payments_update_discounts'
	get 'payments/new/update_ipc/:year/:month', to: 'payments#update_ipc', as: 'payments_update_ipc'
	get 'payments/new/:payment_id/generate_receipt', to: 'payments#generate_payment_receipt', as: 'generate_payment_receipt'
	get 'payments/new/warranty/:administration_number', to: 'payments#new_warranty', as: 'new_warranty_payment'

	# Contracts
	post  'contracts/assign_admin_n', to: 'contracts#assign_admin_n', as: 'assign_admin_n'
	get   'contracts/update_readjustment_fields', to: 'contracts#update_readjustment_fields'
	get   'contracts/:id/show_terminate_form', to: 'contracts#show_terminate_form', as: 'show_termiante_form'
	get   'contracts/:id/show_terminate_form/add_expense/:count', to: 'contracts#add_contract_expense', as: 'add_contract_expense'
	get   'contracts/:id/show_warranty_receipt', to: 'contracts#show_warranty_receipt', as: 'contracts_show_warranty_receipt'
	patch 'contracts/:id/terminate', to: 'contracts#terminate', as: 'terminate_contract'
	get   'contracts/:id/show', to: 'contracts#show', as: 'show_contract'
	get   'contracts/show/discharge/:discharge_id', to: 'contracts#show_discharge', as: 'show_contract_discharge'
	get   'contracts/show/inventory/:inventory_id', to: 'contracts#show_inventory', as: 'show_contract_inventory'
	resources :contracts, except: [:show]

	# Expenses
	get 'expenses/fetch/:property_id', to: 'expenses#fetch_expenses', as: 'fetch_expenses'
	get 'expenses/new/:property_id', to: 'expenses#new', as: 'new_expense'
	get 'expenses/fetch_expense/:id', to: 'expenses#fetch_expense'
	resources :expenses, except: [:new, :show]

	# Associated Documents
	resources :associated_documents

	# Notifications
	resources :notifications

	# Properties
	resources :properties, except: [:show]
	get 'properties/new/:user_id', to: 'properties#new_property'
	get 'properties/new/:user_id/add_administration_beneficiary/:count', to: 'properties#add_administration_beneficiary', as: 'add_administration_beneficiary'
	get 'properties/create_administration_number', to: 'properties#create_administration_number', as: 'create_administration_number'
	get 'properties/assign_administration_number/:admin_n', to: 'properties#assign_administration_number', as: 'assign_administration_number'
	get 'properties/delete/:id', to: 'properties#delete', as: 'delete_property'
	get 'properties/show_mandate/:id', to: 'properties#show_mandate', as: 'show_property_mandate'

	# USERS
	get  'users/delete/:id', to: 'users#delete', as: 'delete_user'
	# Proprietaries
	get  'users/proprietaries', to: 'users#proprietaries'
	get  'users/new/proprietary', to: 'users#new_proprietary'
	get  'users/fetch_properties/:user_id', to: 'users#fetch_properties'
	get  'users/fetch_settlements/:user_id', to: 'users#fetch_settlements'
	post 'users/proprietaries', to: 'users#create_proprietary', as: 'create_proprietary'
	# Tenants
	get  'users/tenants', to: 'users#tenants'
	get  'users/new/tenant', to: 'users#new_tenant'
	get  'users/new/tenant/:administration_number', to: 'users#new_tenant', as: 'create_tenant_with_admin_n'
	post 'users/tenants', to: 'users#create_tenant', as: 'create_tenant'
	get  'users/tenant/:user_id/fetch/payments', to: 'users#fetch_tenant_payments', as: 'fetch_tenant_payments'
	get  'users/tenant/show/payment/receipt/:payment_id', to: 'users#show_tenant_payment_receipt', as: 'show_tenant_payment_receipt'
	get  'users/tenant/show/contract/:contract_id', to: 'users#show_tenant_contract', as: 'show_tenant_contract'
	get  'users/tenant/terminate_contract/:contract_id', to: 'users#show_tenant_terminate_contract_form', as: 'show_tenant_terminate_contract_form'
	resources :users, except: [:index, :show, :new]

	# Administration Numbers
	get 'administration/index', to: 'administration_numbers#index', as: 'administration_numbers'

	# Reports
	get 'reports/collection', to: 'reports#collection', as: 'reports_collection'
	get 'reports/collection_debts/:admin_number', to: 'reports#collection_debts', as: 'reports_collection_debts'
	get 'reports/collection_debts/:admin_number/generate.pdf', to: 'reports#collection_debts', as: 'reports_collection_debts_pdf'
	get 'reports/settlements', to: 'reports#settlements', as: 'reports_settlements'
	get 'reports/property_return', to: 'reports#property_return', as: 'reports_property_return'
	get 'reports/active_administrations', to: 'reports#active_administrations', as: 'reports_active_administrations'
	get 'reports/contributions', to: 'reports#contributions', as: 'reports_contributions'
	get 'reports/expenses', to: 'reports#expenses', as: 'reports_expenses'
	get 'reports/administration_profit', to: 'reports#administration_profit', as: 'reports_administration_profit'
	get 'reports/property_works', to: 'reports#property_works', as: 'reports_property_works'
	get 'reports/unpaid_settlements', to: 'reports#unpaid_settlements', as: 'reports_unpaid_settlements'

	# Property Works
	get   'property_works', to: 'property_works#index', as: 'property_works'
	get   'property_works/show/:property_id', to: 'property_works#show', as: 'show_property_works'
	get   'property_works/new/:property_id', to: 'property_works#new', as: 'new_property_work'
	get   'property_works/new/add_expense/:count', to: 'property_works#add_expense', as: 'property_work_add_expense'
	post  'property_works', to: 'property_works#create'
	patch 'property_works/:id', to: 'property_works#update', as: 'update_property_work'

	# System Control
	get   'system_controls/info', to: 'system_controls#info', as: 'system_info'
	patch 'system_controls/update_info', to: 'system_controls#update_info', as: 'system_update_info'
	get   'system_controls/users', to: 'system_controls#users', as: 'system_users'
	post  'system_controls/users', to: 'system_controls#create_user', as: 'system_create_user'
	get   'system_controls/users/edit/:user_id', to: 'system_controls#edit_user', as: 'system_edit_user'
	patch 'system_controls/users/:user_id', to: 'system_controls#update_user', as: 'system_update_user'
	get   'system_controls/users/deactivate/:user_id', to: 'system_controls#deactivate_user', as: 'system_deactivate_user'
	get   'system_controls/users/activate/:user_id', to: 'system_controls#activate_user', as: 'system_activate_user'
	get   'system_controls/logs', to: 'system_controls#logs', as: 'system_logs'

	# Search
	post 'search', to: 'search#search', as: 'search'

	# Sessions
	resources :sessions, only: [:create, :destroy]
	get  'signup', to: 'users#new', as: 'signup'
	get  'login',  to: 'sessions#new', as: 'login'
	get  'logout', to: 'sessions#destroy', as: 'logout'
	get  'forgot_password', to: 'sessions#forgot_password', as: 'forgot_password'
	post 'restore_password', to: 'sessions#restore_password', as: 'restore_password'


	# Home and login
	get 'home/index', as: 'home'

	# Root definition
	root 'home#index'
end

app/views/partials/_dashboard_card.html.erb
<% color = data == 0 ? 'green' : 'red' %>

<a class="dashboard-card-link" href="<%= href %>">
	<div class="dashboard-card">
		<div class="header"><%= header %></div>
		<div class="data" style="color: <%=color%>;"><%= data %></div>
		<div class="footer" style="color: <%=color%>;"><%= footer %></div>
	</div>
</a>

<style>
	.dashboard-card{
		min-width: 300px;
		min-height: 300px;
		margin: 30px;
		padding: 30px;

		display: flex;
		flex-direction: column;
		justify-content: space-between;

		text-align: center;

		background-color: rgba(242, 242, 242, 1);
		box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.2);
	}

	.dashboard-card-link:hover{
		text-decoration: none;
	}

	.header {
		font-size: 30px
	}

	.data {
		font-size: 60px;
	}

	.footer {
		font-size: 30px
	}
</style>

app/views/partials/_excel_button.html.erb
<p class="h5 mt-1 mb-0" style="cursor: pointer;">
	<!--<i class="fa fa-file-excel text-success" id="excel-button" onclick="helpers.downloadXlsxFromTable('<%= table_id %>', '<%= file_name %>');"></i>-->
	<i class="fa fa-file-excel text-success" id="excel-button"></i>
</p>

<script data-turbolinks="false">
	excelButton = document.getElementById('excel-button');
	excelButton.onclick = function() {
		helpers.downloadXlsxFromTable('<%= table_id %>', '<%= file_name %>');
	}
</script>

app/views/partials/_excel_button_fake_table.html.erb
<p class="h5 mt-1 mb-0" style="cursor: pointer;">
	<i class="fa fa-file-excel text-success" onclick="helpers.downloadXlsxFromFakeTable('<%= table_id %>', '<%= file_name %>');"></i>
</p>

app/views/partials/_file_button.html.erb
<div class="form-group file-button">
	<% btn_class = (previous and f.object.send(file_field).attached?) ? 'btn-success' : 'btn-info' %>
	<%= f.file_field file_field, class: 'd-none file-field', accept: 'image/png,image/jpeg,application/pdf', onchange: 'helpers.fileUploadSuccess(event);' %>
	<%= f.label file_field, label, class: "btn #{btn_class}", style: 'color: white;' %>
	<div class="error"><%= show_errors(f.object, file_field) %></div>
</div>

app/views/partials/_file_button_noform.html.erb
<div class="file-button">
	<% btn_class = (previous and object.send(file_field).attached?) ? 'btn-success' : 'btn-info' %>
	<%= file_field_tag file_field, class: 'd-none file-field', accept: 'image/png,image/jpeg,application/pdf', onchange: 'helpers.fileUploadSuccess(event);' %>
	<%= label_tag file_field, label, class: "btn #{btn_class}", style: 'color: white;' %>
	<div class="error"><%= show_errors(object, file_field) %></div>
</div>

app/views/partials/_flash_alerts.html.erb
<% if alert %>
	<div class="alert alert-danger" id="alert">
		<%= alert %>
	</div>
<% end %>

app/views/partials/_head.html.erb
<head>
  <title>Arrendamiento</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">

  <meta charset="utf-8" />

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true  %>
  <%= javascript_include_tag 'head', 'data-turbolinks-track': 'reload' %>

</head>

app/views/partials/_messages.html.erb
<% if flash[:notice] %>
    <div class="notification is-success">
        <button class="delete" id="delete-notofication"></button>
        <%= flash[:notice] %>
    </div>
<% end %>

app/views/partials/_navbar.html.erb
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
	<form class="form-inline mr-auto">
		<ul class="navbar-nav mr-3">
			<li><span data-toggle="sidebar" class="nav-link nav-link-lg pointer"><i class="fas fa-bars"></i></span></li>
			<li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
		</ul>
	</form>

	<ul class="navbar-nav navbar-right">
		<li>
			<%= link_to logout_path do %>
				<span class="nav-link nav-link-lg pointer"><i class="fas fa-sign-out-alt"></i></span>
			<% end %>
		</li>

		<li class="dropdown">
			<a href="#" class="nav-link nav-link-lg nav-link-user">
				<%= image_tag 'avatar/avatar-1.png', class: 'rounded-circle mr-1', style: 'width: 30' %>
				<% if current_user %>
					<div class="d-sm-none d-lg-inline-block"><%= current_user.name %></div></a>
				<% else %>
					<div class="d-sm-none d-lg-inline-block">No User</div></a>
				<% end %>
			</a>
		</li>
	</ul>
</nav>

app/views/partials/_publication.erb
<div class="card">
    <div class="card-content">
        
        <h1 class="subtitle"><strong><%= @publication.cargo %></strong></h1>

        <div class="columns">
            <div class="column">
                <strong> Fecha:</strong> <%= @publication.fecha %>
            </div>
            <div class="column">
                <strong> Cantidad:</strong> <%= @publication.cantidad %>
            </div>
            <div class="column">
                <strong> Tipo cargo: </strong> <%= @publication.tipo_cargo %>
            </div>

            <div class="column">
                <strong> Ciudad:</strong> <%= @publication.ciudad %>
            </div>
        </div>

        <p>
        <strong>Especificaciones académicas:</strong>
        <%= @publication.especificaciones_academicas %>
        </p>

        <p>
        <strong>Especificaciones laborales:</strong>
        <%= @publication.especificaciones_laborales %>
        </p>
        <br>
        <p>
            <% if @publication.especificaciones_file.attached? %>
                <strong>Descriptor cargo:</strong>
                <%= link_to 'Ver archivo', @publication.especificaciones_file, target: "_blank", class:'button is-info is-outlined' %>
            <% end %>
        </p>
    </div>
</div>

app/views/partials/_search_form.html.erb
<div class="d-flex justify-content-center">
	<%= form_with url: search_path, remote: true do |f| %>
		<!-- Model to perform query -->
		<%= f.text_field :model, value: model, hidden: true %>

		<!-- Init queries -->
		<% if not local_assigns[:init_queries].nil? %>
			<% local_assigns[:init_queries].each_with_index do |init_query, i| %>
				<%= f.text_field 'init_queries['+i.to_s+']', value: init_query, hidden: true %>
			<% end %>
		<% end %>

		<!-- Query constants -->
		<% if not local_assigns[:constants].nil? %>
			<% local_assigns[:constants].each do |key, val| %>
				<%= f.text_field 'constants['+key.to_s+']', value: val, hidden: true %>
			<% end %>
		<% end %>

		<!-- Query vars -->
		<%= f.text_field :search_vars, value: search_vars.to_s, hidden: true %>

		<!-- Meta -->
		<%= f.text_field :table_container_id, value: table_container_id, hidden: true %>
		<%= f.text_field :table_partial, value: table_partial, hidden: true %>
		<%= f.text_field :query_name, value: query_name, hidden: true %>

		<!-- Search term -->
		<div class="input-group">

			<div class="input-group-btn">
				<%= f.submit 'Buscar', class: 'btn btn-primary h-100' %>
			</div>
			<%= f.text_field :search_term, class: 'form-control' %>
		</div>
	<% end %>
</div>


<!--
	<form>
		<div class="input-group">
			<input type="text" class="form-control" placeholder="Buscar <%= @role_name %>">
			<div class="input-group-btn">
				<button class="btn btn-primary"><i class="fas fa-search"></i></button>
			</div>
		</div>
	</form>
-->

app/views/partials/_search_form_with_dates.html.erb
<div class="d-flex justify-content-center">
	<%= form_with url: search_path, remote: true do |f| %>
		<!-- Model to perform query -->
		<%= f.text_field :model, value: model, hidden: true %>

		<!-- Init queries -->
		<% if not local_assigns[:init_queries].nil? %>
			<% local_assigns[:init_queries].each_with_index do |init_query, i| %>
				<%= f.text_field 'init_queries['+i.to_s+']', value: init_query, hidden: true %>
			<% end %>
		<% end %>

		<!-- Query constants -->
		<% if not local_assigns[:constants].nil? %>
			<% local_assigns[:constants].each do |key, val| %>
				<%= f.text_field 'constants['+key.to_s+']', value: val, hidden: true %>
			<% end %>
		<% end %>

		<!-- Query vars -->
		<%= f.text_field :search_vars, value: search_vars.to_s, hidden: true %>

		<!-- Time vars -->
		<%= f.text_field :time_vars, value: time_vars.to_s, hidden: true %>

		<!-- Meta -->
		<%= f.text_field :table_container_id, value: table_container_id, hidden: true %>
		<%= f.text_field :table_partial, value: table_partial, hidden: true %>
		<%= f.text_field :query_name, value: query_name, hidden: true %>

		<!-- Search term -->
		<div class="input-group row">
			<div class="col-sm-4">
				<div class="row">
					<div class="col-sm-3"><%= f.label :from, 'Desde', class: 'control-label' %></div>
					<div class="col-sm-9"><%= f.date_field :from, class: 'form-control' %></div>
				</div>
			</div>

			<div class="col-sm-4">
				<div class="row">
					<div class="col-sm-3"><%= f.label :until, 'Hasta', class: 'control-label' %></div>
					<div class="col-sm-9"><%= f.date_field :until, class: 'form-control' %></div>
				</div>
			</div>

			<div class="col-sm-4">
				<div class="row">
					<div class="col-sm-4 input-group-btn">
						<%= f.submit 'Buscar', class: 'btn btn-primary h-100' %>
					</div>
					<div class="col-sm-8"><%= f.text_field :search_term, class: 'form-control' %></div>
				</div>
			</div>
		</div>
	<% end %>
</div>


<!--
	<form>
		<div class="input-group">
			<input type="text" class="form-control" placeholder="Buscar <%= @role_name %>">
			<div class="input-group-btn">
				<button class="btn btn-primary"><i class="fas fa-search"></i></button>
			</div>
		</div>
	</form>
-->

app/views/partials/_sidebar.html.erb
<div class="main-sidebar">
<aside id="sidebar-wrapper">
  <div class="sidebar-brand">
    <%= image_tag 'logo.jpg', class: 'shadow-light', style: 'width: 50px' %>
    <%= link_to 'CIVITANIC', home_path %>
  </div>
  <div class="sidebar-brand sidebar-brand-sm">
    <a href="index.html">CV</a>
  </div>
  <ul class="sidebar-menu">

    <li class="menu-header mt-4">Menú</li>

    <li>
      <%= link_to root_path, class:['nav-link', current_class?(root_path)] do %>
        <i class="fas fa-fire"></i> <span>Indicadores</span>
      <% end %>
    </li>

    <li class="dropdown <%= current_class?('/users/proprietaries') %> <%= current_class?('/users/new/proprietary') %>">
      <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-user"></i> <span>Propietario</span></a>
      <ul class="dropdown-menu">
        <li><%= link_to 'Ver Propietario', '/users/proprietaries', class:['nav-link', current_class?('/users/proprietaries')] %></li>
        <li><%= link_to 'Crear Propietario', '/users/new/proprietary', class:['nav-link', current_class?('/users/new/proprietary')] %></li>
      </ul>
    </li>

    <li class="dropdown <%= current_class?(properties_path) %> <%= current_class?(new_property_path) %>">
      <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-hotel"></i> <span>Propiedad</span></a>
      <ul class="dropdown-menu ">
        <li><%= link_to 'Ver Propiedad', properties_path, class:['nav-link', current_class?(properties_path)] %></li>
        <li><%= link_to 'Crear Propiedad', new_property_path, class:['nav-link', current_class?(new_property_path)] %></li>
      </ul>
    </li>

    <li class="dropdown  <%= current_class?(users_tenants_path) %> <%= current_class?(users_new_tenant_path) %>">
      <a href="#" class="nav-link has-dropdown"><i class="fas fa-user-tag"></i> <span>Arrendatario</span></a>
      <ul class="dropdown-menu">
        <li><%= link_to 'Ver Arrendatario', users_tenants_path, class:['nav-link', current_class?(users_tenants_path)] %></a></li>
        <li><%= link_to 'Crear Arrendatario', users_new_tenant_path, class:['nav-link', current_class?(users_new_tenant_path)] %></a></li>
      </ul>
    </li>

    <li class="dropdown <%= current_class?(expenses_path) %> <%= current_class?(payments_path) %> <%= current_class?(settlements_path) %>">
      <a href="#" class="nav-link has-dropdown"><i class="fas fa-toolbox"></i> <span>Administración</span></a>
      <ul class="dropdown-menu">
	    <li><%= link_to 'Ingreso de Gastos', expenses_path, class: 'nav-link' %></li>
        <li><%= link_to 'Ingreso de Pagos', payments_path, class: 'nav-link' %></li>
        <li><%= link_to 'Liquidación Propietario', settlements_path, class: 'nav-link' %></li>
        <li><%= link_to 'Trabajos a Propiedad', property_works_path, class: 'nav-link' %></li>
        <li><%= link_to 'Listado de Administración', administration_numbers_path, class: 'nav-link' %></li>
      </ul>
    </li>

    <li class="dropdown">
      <a href="#" class="nav-link has-dropdown"><i class="fas fa-book"></i> <span>Reportes</span></a>
      <ul class="dropdown-menu">
		<li><%= link_to 'Pago Cobranza Arrendatario', reports_collection_path, class: 'nav-link' %></li>
		<li><%= link_to 'Pago a Propietarios', reports_settlements_path, class: 'nav-link' %></li>
		<li><%= link_to 'Trabajos en Propiedades', reports_property_works_path, class: 'nav-link' %></li>
        <li><%= link_to 'Arrendatarios Devuelven Propiedad', reports_property_return_path, class: 'nav-link' %></li>
        <li><%= link_to 'Propietarios en Admin. Vigente', reports_active_administrations_path, class: 'nav-link' %></li>
        <li><%= link_to 'Listados de Contribuciones', reports_contributions_path, class: 'nav-link' %></li>
        <li><%= link_to 'Informe de Gastos', reports_expenses_path, class: 'nav-link' %></li>
        <li><%= link_to 'Listado de Cobros', reports_administration_profit_path, class: 'nav-link' %></li>
      </ul>
    </li>

    <li class="dropdown">
      <a href="#" class="nav-link has-dropdown"><i class="fas fa-file-contract"></i> <span>Contrato</span></a>
      <ul class="dropdown-menu">
        <li><%= link_to 'Ingresar Datos Contrato', new_contract_path, class: ['nav-link'] %></li>
        <li><%= link_to 'Ver Contratos - Inventarios', contracts_path, class: ['nav-link'] %></li>
      </ul>
    </li>

    <li class="dropdown">
      <a href="#" class="nav-link has-dropdown"><i class="fas fa-th"></i> <span>Control Sistema</span></a>
      <ul class="dropdown-menu">
        <li><%= link_to 'Datos de la Empresa', system_info_path, class: ['nav-link'] %></li>
        <li><%= link_to 'Usuarios y Perfiles', system_users_path, class: ['nav-link'] %></li>
        <li><%= link_to 'Ver Eventos del Sistema', system_logs_path, class: ['nav-link'] %></li>
      </ul>
    </li>

</aside>
</div>

app/views/partials/_title.html.erb
<div class="section-header container-fluid d-flex justify-content-between align-items-center">
    <h1><%= title %></h1>
    <div class="row w-40">
        <div class="col-5 text-center">
            <p class="m-0 font-weight-bold"> Fecha </p>
            <p class="m-0"> <%= I18n.l(DateTime.now, format: '%d/%m/%Y', locale: :'es')	 %> </p>
        </div>
        <div class="col-3 text-center">
            <p class="m-0 font-weight-bold"> Hora </p>
            <p class="m-0"> <%= I18n.l(DateTime.now, format: '%H:%M:%S', locale: :'es')	 %> </p>
        </div>
        <div class="col-4 text-center">
            <p class="m-0 font-weight-bold"> UF de Hoy </p>
            <p class="m-0"> <%= get_UF %> </p>
        </div>
    </div>
</div>