config/routes.rb
Rails.application.routes.draw do

	# Settlemets
	get 'settlements/fetch_settlements/:contract_id', to: 'settlements#fetch_settlements', as: 'fetch_settlements'
	get 'settlement/settlement_pdf/:id', to: 'settlements#settlement_pdf', as: 'settlement_pdf'
	get 'settlements/new/:contract_id', to: 'settlements#new', as: 'new_settlement'
	resources :settlements, except: [:new, :show, :destroy]

	# Payments
	resources :payments, except: [:new, :show]
	get 'payments/show_proprietary_payment/:administration_number', to: 'payments#show_proprietary_payment', as: 'show_proprietary_payment'
	get 'payments/:administration_number/generate_warranty_receipt', to: 'payments#generate_warranty_receipt', as: 'generate_warranty_receipt'
	get 'payments/new/:administration_number', to: 'payments#new', as: 'new_payment'
	get 'payments/new/update_discounts/:administration_number/:month', to: 'payments#update_discounts', as: 'payments_update_discounts'
	get 'payments/new/update_ipc/:year/:month', to: 'payments#update_ipc', as: 'payments_update_ipc'
	get 'payments/new/:payment_id/generate_receipt', to: 'payments#generate_payment_receipt', as: 'generate_payment_receipt'
	get 'payments/new/warranty/:administration_number', to: 'payments#new_warranty', as: 'new_warranty_payment'

	# Contracts
	post  'contracts/assign_admin_n', to: 'contracts#assign_admin_n', as: 'assign_admin_n'
	get   'contracts/update_readjustment_fields', to: 'contracts#update_readjustment_fields'
	get   'contracts/:id/show_terminate_form', to: 'contracts#show_terminate_form', as: 'show_termiante_form'
	get   'contracts/:id/show_terminate_form/add_expense/:count', to: 'contracts#add_contract_expense', as: 'add_contract_expense'
	get   'contracts/:id/show_warranty_receipt', to: 'contracts#show_warranty_receipt', as: 'contracts_show_warranty_receipt'
	patch 'contracts/:id/terminate', to: 'contracts#terminate', as: 'terminate_contract'
	get   'contracts/:id/show', to: 'contracts#show', as: 'show_contract'
	get   'contracts/show/discharge/:discharge_id', to: 'contracts#show_discharge', as: 'show_contract_discharge'
	get   'contracts/show/inventory/:inventory_id', to: 'contracts#show_inventory', as: 'show_contract_inventory'
	resources :contracts, except: [:show]

	# Expenses
	get 'expenses/fetch/:property_id', to: 'expenses#fetch_expenses', as: 'fetch_expenses'
	get 'expenses/new/:property_id', to: 'expenses#new', as: 'new_expense'
	get 'expenses/fetch_expense/:id', to: 'expenses#fetch_expense'
	resources :expenses, except: [:new, :show]

	# Associated Documents
	resources :associated_documents

	# Notifications
	resources :notifications

	# Properties
	resources :properties, except: [:show]
	get 'properties/new/:user_id', to: 'properties#new_property'
	get 'properties/new/:user_id/add_administration_beneficiary/:count', to: 'properties#add_administration_beneficiary', as: 'add_administration_beneficiary'
	get 'properties/create_administration_number', to: 'properties#create_administration_number', as: 'create_administration_number'
	get 'properties/assign_administration_number/:admin_n', to: 'properties#assign_administration_number', as: 'assign_administration_number'
	get 'properties/delete/:id', to: 'properties#delete', as: 'delete_property'
	get 'properties/show_mandate/:id', to: 'properties#show_mandate', as: 'show_property_mandate'

	# USERS
	get  'users/delete/:id', to: 'users#delete', as: 'delete_user'
	# Proprietaries
	get  'users/proprietaries', to: 'users#proprietaries'
	get  'users/new/proprietary', to: 'users#new_proprietary'
	get  'users/fetch_properties/:user_id', to: 'users#fetch_properties'
	get  'users/fetch_settlements/:user_id', to: 'users#fetch_settlements'
	post 'users/proprietaries', to: 'users#create_proprietary', as: 'create_proprietary'
	# Tenants
	get  'users/tenants', to: 'users#tenants'
	get  'users/new/tenant', to: 'users#new_tenant'
	get  'users/new/tenant/:administration_number', to: 'users#new_tenant', as: 'create_tenant_with_admin_n'
	post 'users/tenants', to: 'users#create_tenant', as: 'create_tenant'
	get  'users/tenant/:user_id/fetch/payments', to: 'users#fetch_tenant_payments', as: 'fetch_tenant_payments'
	get  'users/tenant/show/payment/receipt/:payment_id', to: 'users#show_tenant_payment_receipt', as: 'show_tenant_payment_receipt'
	get  'users/tenant/show/contract/:contract_id', to: 'users#show_tenant_contract', as: 'show_tenant_contract'
	get  'users/tenant/terminate_contract/:contract_id', to: 'users#show_tenant_terminate_contract_form', as: 'show_tenant_terminate_contract_form'
	resources :users, except: [:index, :show, :new]

	# Administration Numbers
	get 'administration/index', to: 'administration_numbers#index', as: 'administration_numbers'

	# Reports
	get 'reports/collection', to: 'reports#collection', as: 'reports_collection'
	get 'reports/collection_debts/:admin_number', to: 'reports#collection_debts', as: 'reports_collection_debts'
	get 'reports/collection_debts/:admin_number/generate.pdf', to: 'reports#collection_debts', as: 'reports_collection_debts_pdf'
	get 'reports/settlements', to: 'reports#settlements', as: 'reports_settlements'
	get 'reports/property_return', to: 'reports#property_return', as: 'reports_property_return'
	get 'reports/active_administrations', to: 'reports#active_administrations', as: 'reports_active_administrations'
	get 'reports/contributions', to: 'reports#contributions', as: 'reports_contributions'
	get 'reports/expenses', to: 'reports#expenses', as: 'reports_expenses'
	get 'reports/administration_profit', to: 'reports#administration_profit', as: 'reports_administration_profit'
	get 'reports/property_works', to: 'reports#property_works', as: 'reports_property_works'
	get 'reports/unpaid_settlements', to: 'reports#unpaid_settlements', as: 'reports_unpaid_settlements'

	# Property Works
	get   'property_works', to: 'property_works#index', as: 'property_works'
	get   'property_works/show/:property_id', to: 'property_works#show', as: 'show_property_works'
	get   'property_works/new/:property_id', to: 'property_works#new', as: 'new_property_work'
	get   'property_works/new/add_expense/:count', to: 'property_works#add_expense', as: 'property_work_add_expense'
	post  'property_works', to: 'property_works#create'
	patch 'property_works/:id', to: 'property_works#update', as: 'update_property_work'

	# System Control
	get   'system_controls/info', to: 'system_controls#info', as: 'system_info'
	patch 'system_controls/update_info', to: 'system_controls#update_info', as: 'system_update_info'
	get   'system_controls/users', to: 'system_controls#users', as: 'system_users'
	post  'system_controls/users', to: 'system_controls#create_user', as: 'system_create_user'
	get   'system_controls/users/edit/:user_id', to: 'system_controls#edit_user', as: 'system_edit_user'
	patch 'system_controls/users/:user_id', to: 'system_controls#update_user', as: 'system_update_user'
	get   'system_controls/users/deactivate/:user_id', to: 'system_controls#deactivate_user', as: 'system_deactivate_user'
	get   'system_controls/users/activate/:user_id', to: 'system_controls#activate_user', as: 'system_activate_user'
	get   'system_controls/logs', to: 'system_controls#logs', as: 'system_logs'

	# Search
	post 'search', to: 'search#search', as: 'search'

	# Sessions
	resources :sessions, only: [:create, :destroy]
	get  'signup', to: 'users#new', as: 'signup'
	get  'login',  to: 'sessions#new', as: 'login'
	get  'logout', to: 'sessions#destroy', as: 'logout'
	get  'forgot_password', to: 'sessions#forgot_password', as: 'forgot_password'
	post 'restore_password', to: 'sessions#restore_password', as: 'restore_password'


	# Home and login
	get 'home/index', as: 'home'

	# Root definition
	root 'home#index'
end

app/models/property.rb
class Property < ActiveRecord::Base
	# Associations
	has_many :property_has_expenses, dependent: :destroy
	has_many :expenses, through: :property_has_expenses, dependent: :destroy
	has_many :property_works, dependent: :destroy
	has_one :common_expenses_administrator, dependent: :destroy
	has_many :administration_beneficiaries, dependent: :destroy
	has_one :administration_number

	accepts_nested_attributes_for :common_expenses_administrator
	accepts_nested_attributes_for :administration_beneficiaries, allow_destroy: true

	# Validations
	validates_presence_of :property_type, :region, :commune, :water_ias,
						  :electricity_ias, :gas_ias, :address,
						  :adm_percentage, :administration_number
	validates_inclusion_of :common_expenses, in: [true, false]
	validates_inclusion_of :adm_rent, in: [true, false]
	validates_inclusion_of :adm_contributions, in: [true, false]
	validates_inclusion_of :adm_common_expenses, in: [true, false]
	validate{
		if not (self.adm_rent or self.adm_contributions or
				self.adm_common_expenses or self.adm_other.strip.length != 0)
			error_str = 'Debe elegir almenos una'
			self.errors.add(:adm_rent, error_str)
			self.errors.add(:adm_contributions, error_str)
			self.errors.add(:adm_common_expenses, error_str)
			self.errors.add(:adm_other, error_str)
		end
	}

	validates_associated :common_expenses_administrator
	validates_associated :administration_beneficiaries
	validate :common_expenses_administrator_inclusion

	# Mandate file
	has_one_attached :mandate
	include FileValidation
	#validate {
	#	file_validation(:mandate)
	#}

	after_rollback {
		file_delete(:mandate)
	}

	# Enums
	include Commune
	include Region

	# Property Type
	TYPE_STR = {
		:office		 => 'Oficina',
		:local		 => 'Local',
		:site		 => 'Sitio',
		:house		 => 'Casa',
		:apartment	 => 'Departamento',
		:parking_lot => 'Estacionamiento',
		:industrial  => 'Industrial',
		:cellar		 => 'Bodega',
		:shed		 => 'Galpon',
	}
	enum property_type: TYPE_STR.keys

	# State
	STATE_STR = {
		:available		=> 'Disponible',
		:rented			=> 'Arrendada',
		:for_repairment => 'Por Reparacion',
	}
	enum state: STATE_STR.keys

	def type_string
		TYPE_STR[self.property_type.to_sym]
	end

	def state_string
		STATE_STR[self.state.to_sym]
	end

	def self.type_collection
		TYPE_STR.invert
	end

	def self.state_collection
		STATE_STR.invert
	end

	def self.common_expenses_collection
		{
			'No' => false,
			'Si' => true
		}
	end

	def contributions_amount
		self.property_role_contribution + self.cellar_role_contribution + self.parking_role_contribution
	end

	def active_property_works
		PropertyWork.where(property: self, finished: false)
	end

	private

		def common_expenses_administrator_inclusion
			has_administrator = false
			if self.common_expenses_administrator
				has_administrator = true
			end

			if self.common_expenses == (not has_administrator)
				if self.common_expenses
					self.errors.add(:common_expenses_administrator, message: "Debe tener administracion de gastos comunes")
				else
					self.errors.add(:common_expenses_administrator, message: "Tratando de romper mi sistema?")
				end
			end
		end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
	before_action only:   [:index, :edit, :show_mandate] do authorize_read(Property) end
	before_action except: [:index, :edit, :show_mandate] do authorize_manage(Property) end

	def index
		@properties = Property.all
	end

	def new
		@users = User.proprietary
	end

	def new_property
		@user = User.find(params[:user_id])
		@property = Property.new
		@property.common_expenses_administrator = CommonExpensesAdministrator.new
		@property.administration_beneficiaries.build
		@admin_n = nil
	end

	def edit
		@property = Property.find(params[:id])
		puts @property.inspect
		if not @property.common_expenses_administrator
			@property.build_common_expenses_administrator
		end
		@user = @property.administration_number.proprietary
	end

	def create
		es_to_en_str!(params[:property][:water_ias])
		es_to_en_str!(params[:property][:electricity_ias])
		es_to_en_str!(params[:property][:gas_ias])
		es_to_en_str!(params[:property][:adm_percentage])
		params[:property][:administration_beneficiaries_attributes].each do |k, v|
			es_to_en_str!(v[:percentage])
		end

		@user = User.find(params[:user_id])
		@property = Property.new(property_params)
		@property.state = :available

		# Lookup admin_n if it was present
		if params[:administration_number] != ""
			@admin_n = AdministrationNumber.find(params[:administration_number])
		else
			@admin_n = nil
		end

		# Check if an admin_n was present and if it has no property associated
		if @admin_n != nil and @admin_n.property == nil
			@admin_n.property = @property
			@admin_n.proprietary = @user
		elsif @admin_n == nil
			@property.valid?
			@property.errors.add(:administration_number_select, 'Debe asignar un número de administración')
		elsif @admin_n.property != nil
			@property.valid?
			@property.errors.add(:administration_number_select, "La administración #{@admin_n.id} ya no está disponible")
		end

		if @property.errors.empty? and @property.save and @admin_n.save
			LogEntry.create user: current_user, datetime: DateTime.now, action: 'creó', model: 'propiedad', description: "N ADM #{@property.administration_number.id}"
			redirect_to properties_path
		else
			signal_form_errors
			if @property.common_expenses_administrator == nil
				@property.common_expenses_administrator = CommonExpensesAdministrator.new
			end
			render 'new_property'
		end
	end

	def update
		es_to_en_str!(params[:property][:water_ias])
		es_to_en_str!(params[:property][:electricity_ias])
		es_to_en_str!(params[:property][:gas_ias])
		es_to_en_str!(params[:property][:property_role_contribution])
		es_to_en_str!(params[:property][:parking_role_contribution])
		es_to_en_str!(params[:property][:cellar_role_contribution])
		es_to_en_str!(params[:property][:adm_percentage])
		params[:property][:administration_beneficiaries_attributes].each do |k, v|
			es_to_en_str!(v[:percentage])
		end

		@property = Property.find(params[:id])

		if @property.update(property_params)
			LogEntry.create user: current_user, datetime: DateTime.now, action: 'editó', model: 'propiedad', description: "N ADM #{@property.administration_number.id}"
			@properties = Property.all
			render 'fetch_properties'
		else
			puts @property.errors.inspect
			@user = @property.administration_number.proprietary
			render 'edit'
		end
	end

	def delete
		@property = Property.find(params[:id])
	end

	def destroy
		@property = Property.find(params[:id])

		if @property.state.to_sym == :available
			@property.administration_number.release_property
			admin_n = @property.administration_number.id
			@property.destroy
			LogEntry.create user: current_user, datetime: DateTime.now, action: 'eliminó', model: 'propiedad', description: "N ADM #{admin_n}"
		end

		@properties = Property.all
		render 'fetch_properties'
	end

	# AJAX APIs
	def add_administration_beneficiary
		@user = User.find(params[:user_id])
		@property = Property.new
		@count = params[:count].to_i
		@count.times{ @property.administration_beneficiaries.build }
	end

	def create_administration_number
		admin_n = AdministrationNumber.create
		LogEntry.create user: current_user, datetime: DateTime.now, action: 'creó', model: 'administración', description: "N ADM #{admin_n.id}"
		params[:admin_n] = admin_n.id
		assign_administration_number
		render 'assign_administration_number'
	end

	def assign_administration_number
		if not ['', '-1'].include? params[:admin_n]
			@admin_n = AdministrationNumber.find(params[:admin_n])
		else
			@admin_n = AdministrationNumber.new
		end

	end

	def show_mandate
		@property = Property.find(params[:id])
	end

	private

		def property_params
			params.require(:property)
				.permit(
					:property_type, :region, :commune, :common_expenses,
					:property_role_contribution, :parking_role_contribution,
					:cellar_role_contribution, :water_ias, :electricity_ias,
					:gas_ias, :address, :state, :adm_percentage, :adm_rent,
					:adm_contributions, :adm_common_expenses, :adm_other,
					:observations, :mandate,

					common_expenses_administrator_attributes: CommonExpensesAdministrator.attribute_names.map(&:to_sym).push(:_destroy),

					administration_beneficiaries_attributes: AdministrationBeneficiary.attribute_names.map(&:to_sym).push(:_destroy))
		end

end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_administration_number_aux.html.erb
<%= simple_form_for @property do |f| %>
	<%= render "fields_create_administration", f: f %>
<% end %>

app/views/properties/_fields_create_administration.html.erb
<div class="col-11">
	<div class="row">
		<div class="form-group col-md-4 justify-content-center">
			<div class="w-75">
				<%= label_tag  :administration_number_select, 'Nº de Administración  Disponibles', class: 'control-label' %>
				<%= select_tag :administration_number_select, options_for_select(AdministrationNumber.without_proprietary_collection), class: 'form-control', id: 'administration-number-select', onchange: 'completeUrl();' %>
				<div class='error'><%= show_errors(@property, :administration_number_select) %></div>
				<%= number_field_tag :administration_number, @admin_n ? @admin_n.id : nil, id: 'admin-n-field', hidden: true %>
				<%= text_field_tag :proprietary_name, @user.name, hidden: true %>

			</div>
		</div>

		<div class="col-3 pl-5">
			<%= link_to 'Asignar Nº ADM', assign_administration_number_path(-1), class: 'btn btn-info w-100 mb-3', id: 'assign-administration-number', remote: true %>
			<%= link_to 'Crear Nº ADM', create_administration_number_path, class: 'btn btn-primary w-100', remote: true %>
		</div>

		<div class="col-5">
			<div class="d-flex flex-column align-items-center">
				<div>
					<p class="lead font-weight-bold mb-4">Nº de Administración: <span id="admin-n" class="h2"><%= @admin_n ? @admin_n.id : '' %></span> </p>
					<p class="font-weight-bold mb-4">Dirección: <span id="address" class="font-weight-normal"><%= f.object.address %></span> </p>
					<p class="font-weight-bold mb-4">Propietario: <span id="proprietary" class="font-weight-normal"><%= @user.name %></span> </p>
					<p class="font-weight-bold mb-4">Nº de Arrendatario: <span id="tenant-n" class="font-weight-normal"><%= @admin_n ? '-' : '' %></span> </p>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
	function completeUrl(){
		var assignLink = document.getElementById('assign-administration-number');
		var administrationNumberSelect = document.getElementById('administration-number-select');
		href = assignLink.href.split('/');
		href[href.length -1] = administrationNumberSelect.value;
		href = href.join('/');
		assignLink.href = href;
	}

	completeUrl();
</script>

app/views/properties/_fields_mandate.html.erb
<div class="form-group col-md-4">
	<%= f.input :adm_percentage, label: '% de Administración', input_html: {type: 'text', class: 'currency-field'} %>
</div>

<div class="form-group col-md-8">
	<%= label_tag :admin_tasks,'Tareas de la Administración', class: 'control-label' %>
	<div class="d-flex align-items-center">
		<div class="form-check">
			<%= f.input_field :adm_rent, as: :boolean, value: '1', class: 'form-check-input' %>
			<%= f.label		  :adm_rent, 'Arriendo', class: 'form-check-label' %>
		</div>

		<div class="form-check">
			<%= f.input_field :adm_common_expenses, as: :boolean, value: '3', class: 'form-check-input' %>
			<%= f.label       :adm_common_expenses, 'Gastos Comunes', class: 'form-check-label' %>
		</div>

		<div class="form-check">
			<%= f.input_field :adm_contributions, as: :boolean, value: '2', class: 'form-check-input' %>
			<%= f.label		  :adm_contributions, 'Contribuciones', class: 'form-check-label' %>
		</div>

		<div class="form-inline ml-2">
			<div class="form-group">
				<%= f.input :adm_other, label: 'Otros' %>
			</div>
		</div>
	</div>
</div>

app/views/properties/_fields_mandate_observations.html.erb
<div class="form-group col-md-12">
	<%= f.input :observations, label: 'Observaciones', input_html: {rows: 5} %>
</div>

app/views/properties/_fields_property.html.erb
<div class="form-group col-md-4">
	<%= f.input :property_type, collection: Property.type_collection, label: 'Tipo Propiedad', include_blank: false %>
</div>

<div class="form-group col-md-8">
	<%= f.input :address, label: 'Dirección', placeholder: 'Dirección', input_html: {id: 'address-field'} %>
</div>

<div class="form-group col-md-4">
	<%= f.input :region, collection: Property.region_collection, label: 'Región', include_blank: false, input_html: {onchange: 'helpers.updateCommuneByRegion(event.target.value, "commune-select");', id: 'region-select'} %>
</div>

<div class="form-group col-md-4">
	<%= f.input :commune, collection: Property.commune_collection, label: 'Comuna', include_blank: false, input_html: {id: 'commune-select'} %>
</div>

<div class="form-group col-md-4">
	<%= f.input :common_expenses, collection: Property.common_expenses_collection, label: 'Gastos Comunes', include_blank: false, input_html: {id: 'common-expenses'} %>
</div>

<div class="form-group col-md-4">
	<%= f.input :property_role_contribution, label: 'Contribución Propiedad', placeholder: 'Contribución Propiedad' %>
</div>

<div class="form-group col-md-4">
	<%= f.input :parking_role_contribution, label: 'Contribución Estacionamiento', placeholder: 'Contribución Estacionamiento' %>
</div>

<div class="form-group col-md-4">
	<%= f.input :cellar_role_contribution, label: 'Contribución Bodega', placeholder: 'Contribución Bodega' %>
</div>

<%= number_field_tag :user_id, @user.id, hidden: true, id: 'user-id' %>

<% content_for :extra_js do %>
	var currentRegion = document.getElementById('region-select').value;
	helpers.updateCommuneByRegion(currentRegion, 'commune-select')
<% end %>

<script>
	if (typeof helpers != 'undefined') {
		var currentRegion = document.getElementById('region-select').value;
		helpers.updateCommuneByRegion(currentRegion, 'commune-select')
	}
</script>

app/views/properties/_fields_services.html.erb
<div class="form-group col-md-12">
	<%= f.input :water_ias, label: 'NIC Aguas', placeholder: 'NIC Aguas', input_html: {min: 0} %>
</div>

<div class="form-group col-md-12">
	<%= f.input :electricity_ias, label: 'NIC Electricidad', placeholder: 'NIC Electricidad', input_html: {min: 0} %>
</div>

<div class="form-group col-md-12">
	<%= f.input :gas_ias, label: 'NIC Gas', placeholder: 'NIC Gas', input_html: {min: 0} %>
</div>

app/views/properties/_form.html.erb
<div class="card">
	<%= render 'partials/flash_alerts' %>

	<%= simple_form_for @property do |f| %>

		<!-- Tabs -->
		<ul class="nav nav-tabs" role="tablist">
			<li class="nav-item">
				<a class="nav-link active" id="property-tab1" data-toggle="tab" href="#info_basic" role="tab" aria-controls="home" aria-selected="true">Información Básica</a>
			</li>

			<li class="nav-item">
				<a class="nav-link" id="admin-tab2" data-toggle="tab" href="#admin" role="tab" aria-controls="admin" aria-selected="false">Mandato Administración</a>
			</li>

			<li class="nav-item">
				<a class="nav-link" id="create-admin-tab2" data-toggle="tab" href="#create_admin" role="tab" aria-controls="contact" aria-selected="false">Crear Administración</a>
			</li>
		</ul>

		<div class="tab-content tab-bordered">

			<!-- Basic information tab -->
			<div class="tab-pane fade show active min-height-500px " id="info_basic" role="tabpanel" aria-labelledby="property-tab1">

				<div class="row">
					<!-- Property fields -->
					<div class="col-12 col-md-9">
						<div class="form-row bordered">
							<%= render 'fields_property', f: f %>
						</div>
					</div>

					<!-- Services fields -->
					<div class="col-12 col-md-3">
						<div class="form-row border p-2">
							<%= render 'fields_services', f: f %>
						</div>
					</div>
				</div>

				<!-- Common expenses fields -->
				<div id="common-expenses-container" class="form-row border p-2 mt-3">
					<%= f.fields_for :common_expenses_administrator do |ceaf| %>
						<%= render 'fields_common_expenses', f: ceaf %>
					<% end %>
				</div>

			</div>

			<!-- Mandate tab -->
			<div class="tab-pane fade min-height-500px" id="admin" role="tabpanel" aria-labelledby="admin-tab2">

				<div class="row justify-content-center">
					<div class="col-11">
						<div class="form-row">
							<%= render 'fields_mandate', f: f %>
						</div>
					</div>

					<div class="col-11">
						<%= render 'fields_mandate_observations', f: f %>
					</div>
				</div>

				<%= render 'fields_mandate_beneficiaries', f: f %>


				<%#= f.input :mandate, label: 'Subir Mandato', input_html: {class: 'd-none', accept: 'image/png,image/jpeg,application/pdf'}, label_html: {class: 'btn btn-info', style: 'color: white;'}%>

				<%= render 'partials/file_button', f: f, file_field: :mandate, label: 'Subir Mandato', previous: true %>
			</div>

			<!-- Create administration tab -->
			<div class="tab-pane fade min-height-500px" id="create_admin" role="tabpanel" aria-labelledby="create-admin-tab2">
				<div class="min-height-500px row align-items-center justify-content-center p-4">

					<div id="create-administration-wrapper">
						<%= render 'fields_create_administration', f: f %>
					</div>

					<div class="col-12 align-self-end">
						<div class="d-flex justify-content-end">
							<%= link_to 'Cancelar', properties_path, class: 'btn btn-danger btn-lg mr-4' %>
							<% if can? :manage, @property %><%= f.submit 'Guardar', class: "btn btn-success btn-lg", onclick: 'modal.showProcessing();' %><% end %>
						</div>
					</div>

				</div>
			</div>

		</div>
	<% end %>
</div>

<%= content_for :extra_js do %>
	setCommonExpensesDisable();
	helpers.setFloatFieldListenerByClass('currency-field');
<% end %>
<script>
	if (typeof helpers != 'undefined') {
		helpers.setFloatFieldListenerByClass('currency-field');
	}
</script>

app/views/properties/_table.html.erb
<table class="table table-bordered table-responsive-sm" id="properties-actual-table">
	<thead class="thead-dark">
		<tr class="text-center">
			<th>Nº ADM</th>
			<th>Nombre Propietario</th>
			<th>Dirección Propiedad</th>
			<th>Nombre Arrendatario</th>
			<th>Estado Propiedad</th>
			<th>Acciones</th>
		</tr>
	</thead>
	<tbody>

		<% properties.each do |property| %>
			<% if can? :read, property %>
				<% tenant_name = property.administration_number.tenant ? property.administration_number.tenant.name : '-' %>

				<tr class="text-center">
					<td><%= property.administration_number ? property.administration_number.id : '-' %></td>
					<td><%= property.administration_number ? property.administration_number.proprietary.name : '-' %></td>
					<td><%= property.address %></td>
					<td><%= tenant_name %></td>
					<td><%= property.state_string %></td>
					<td>
						<div class="dropdown d-inline">
							<button class="btn btn-whitesmoke dropdown-toggle text-danger" type="button" id="dropdownMenuButton4" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Acciones
							</button>
							<div class="dropdown-menu">
								<%= link_to 'Ver Ficha', edit_property_path(property), class: 'dropdown-item', remote: true %>
								<%= link_to 'Ver Mandato', show_property_mandate_path(property), class: 'dropdown-item', remote: true %>
								<% if property.available? and can? :manage, User %> <%= link_to 'Crear Arrendatario', create_tenant_with_admin_n_path(property.administration_number), class: 'dropdown-item' %> <% end %>
								<% if can? :destroy, property %><%= link_to 'Eliminar Propiedad', delete_property_path(property.id), class: 'dropdown-item pointer', remote: true %><% end %>
							</div>
						</div>
					</td>
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>

app/views/properties/edit.js.erb
modal.configXl()
modal.setHeader('Ficha Propiedad');
modal.setBody('<%= j render "form_remote" %>');
setCommonExpensesDisable();
modal.show();

app/views/properties/fetch_properties.js.erb
$('#properties-table').html('<%= j render "table", properties: @properties %>');