config/routes.rb
Rails.application.routes.draw do

	# Settlemets
	get 'settlements/fetch_settlements/:contract_id', to: 'settlements#fetch_settlements', as: 'fetch_settlements'
	get 'settlement/settlement_pdf/:id', to: 'settlements#settlement_pdf', as: 'settlement_pdf'
	get 'settlements/new/:contract_id', to: 'settlements#new', as: 'new_settlement'
	resources :settlements, except: [:new, :show, :destroy]

	# Payments
	resources :payments, except: [:new, :show]
	get 'payments/show_proprietary_payment/:administration_number', to: 'payments#show_proprietary_payment', as: 'show_proprietary_payment'
	get 'payments/:administration_number/generate_warranty_receipt', to: 'payments#generate_warranty_receipt', as: 'generate_warranty_receipt'
	get 'payments/new/:administration_number', to: 'payments#new', as: 'new_payment'
	get 'payments/new/update_discounts/:administration_number/:month', to: 'payments#update_discounts', as: 'payments_update_discounts'
	get 'payments/new/update_ipc/:year/:month', to: 'payments#update_ipc', as: 'payments_update_ipc'
	get 'payments/new/:payment_id/generate_receipt', to: 'payments#generate_payment_receipt', as: 'generate_payment_receipt'
	get 'payments/new/warranty/:administration_number', to: 'payments#new_warranty', as: 'new_warranty_payment'

	# Contracts
	post  'contracts/assign_admin_n', to: 'contracts#assign_admin_n', as: 'assign_admin_n'
	get   'contracts/update_readjustment_fields', to: 'contracts#update_readjustment_fields'
	get   'contracts/:id/show_terminate_form', to: 'contracts#show_terminate_form', as: 'show_termiante_form'
	get   'contracts/:id/show_terminate_form/add_expense/:count', to: 'contracts#add_contract_expense', as: 'add_contract_expense'
	get   'contracts/:id/show_warranty_receipt', to: 'contracts#show_warranty_receipt', as: 'contracts_show_warranty_receipt'
	patch 'contracts/:id/terminate', to: 'contracts#terminate', as: 'terminate_contract'
	get   'contracts/:id/show', to: 'contracts#show', as: 'show_contract'
	get   'contracts/show/discharge/:discharge_id', to: 'contracts#show_discharge', as: 'show_contract_discharge'
	get   'contracts/show/inventory/:inventory_id', to: 'contracts#show_inventory', as: 'show_contract_inventory'
	resources :contracts, except: [:show]

	# Expenses
	get 'expenses/fetch/:property_id', to: 'expenses#fetch_expenses', as: 'fetch_expenses'
	get 'expenses/new/:property_id', to: 'expenses#new', as: 'new_expense'
	get 'expenses/fetch_expense/:id', to: 'expenses#fetch_expense'
	resources :expenses, except: [:new, :show]

	# Associated Documents
	resources :associated_documents

	# Notifications
	resources :notifications

	# Properties
	resources :properties, except: [:show]
	get 'properties/new/:user_id', to: 'properties#new_property'
	get 'properties/new/:user_id/add_administration_beneficiary/:count', to: 'properties#add_administration_beneficiary', as: 'add_administration_beneficiary'
	get 'properties/create_administration_number', to: 'properties#create_administration_number', as: 'create_administration_number'
	get 'properties/assign_administration_number/:admin_n', to: 'properties#assign_administration_number', as: 'assign_administration_number'
	get 'properties/delete/:id', to: 'properties#delete', as: 'delete_property'
	get 'properties/show_mandate/:id', to: 'properties#show_mandate', as: 'show_property_mandate'

	# USERS
	get  'users/delete/:id', to: 'users#delete', as: 'delete_user'
	# Proprietaries
	get  'users/proprietaries', to: 'users#proprietaries'
	get  'users/new/proprietary', to: 'users#new_proprietary'
	get  'users/fetch_properties/:user_id', to: 'users#fetch_properties'
	get  'users/fetch_settlements/:user_id', to: 'users#fetch_settlements'
	post 'users/proprietaries', to: 'users#create_proprietary', as: 'create_proprietary'
	# Tenants
	get  'users/tenants', to: 'users#tenants'
	get  'users/new/tenant', to: 'users#new_tenant'
	get  'users/new/tenant/:administration_number', to: 'users#new_tenant', as: 'create_tenant_with_admin_n'
	post 'users/tenants', to: 'users#create_tenant', as: 'create_tenant'
	get  'users/tenant/:user_id/fetch/payments', to: 'users#fetch_tenant_payments', as: 'fetch_tenant_payments'
	get  'users/tenant/show/payment/receipt/:payment_id', to: 'users#show_tenant_payment_receipt', as: 'show_tenant_payment_receipt'
	get  'users/tenant/show/contract/:contract_id', to: 'users#show_tenant_contract', as: 'show_tenant_contract'
	get  'users/tenant/terminate_contract/:contract_id', to: 'users#show_tenant_terminate_contract_form', as: 'show_tenant_terminate_contract_form'
	resources :users, except: [:index, :show, :new]

	# Administration Numbers
	get 'administration/index', to: 'administration_numbers#index', as: 'administration_numbers'

	# Reports
	get 'reports/collection', to: 'reports#collection', as: 'reports_collection'
	get 'reports/collection_debts/:admin_number', to: 'reports#collection_debts', as: 'reports_collection_debts'
	get 'reports/collection_debts/:admin_number/generate.pdf', to: 'reports#collection_debts', as: 'reports_collection_debts_pdf'
	get 'reports/settlements', to: 'reports#settlements', as: 'reports_settlements'
	get 'reports/property_return', to: 'reports#property_return', as: 'reports_property_return'
	get 'reports/active_administrations', to: 'reports#active_administrations', as: 'reports_active_administrations'
	get 'reports/contributions', to: 'reports#contributions', as: 'reports_contributions'
	get 'reports/expenses', to: 'reports#expenses', as: 'reports_expenses'
	get 'reports/administration_profit', to: 'reports#administration_profit', as: 'reports_administration_profit'
	get 'reports/property_works', to: 'reports#property_works', as: 'reports_property_works'
	get 'reports/unpaid_settlements', to: 'reports#unpaid_settlements', as: 'reports_unpaid_settlements'

	# Property Works
	get   'property_works', to: 'property_works#index', as: 'property_works'
	get   'property_works/show/:property_id', to: 'property_works#show', as: 'show_property_works'
	get   'property_works/new/:property_id', to: 'property_works#new', as: 'new_property_work'
	get   'property_works/new/add_expense/:count', to: 'property_works#add_expense', as: 'property_work_add_expense'
	post  'property_works', to: 'property_works#create'
	patch 'property_works/:id', to: 'property_works#update', as: 'update_property_work'

	# System Control
	get   'system_controls/info', to: 'system_controls#info', as: 'system_info'
	patch 'system_controls/update_info', to: 'system_controls#update_info', as: 'system_update_info'
	get   'system_controls/users', to: 'system_controls#users', as: 'system_users'
	post  'system_controls/users', to: 'system_controls#create_user', as: 'system_create_user'
	get   'system_controls/users/edit/:user_id', to: 'system_controls#edit_user', as: 'system_edit_user'
	patch 'system_controls/users/:user_id', to: 'system_controls#update_user', as: 'system_update_user'
	get   'system_controls/users/deactivate/:user_id', to: 'system_controls#deactivate_user', as: 'system_deactivate_user'
	get   'system_controls/users/activate/:user_id', to: 'system_controls#activate_user', as: 'system_activate_user'
	get   'system_controls/logs', to: 'system_controls#logs', as: 'system_logs'

	# Search
	post 'search', to: 'search#search', as: 'search'

	# Sessions
	resources :sessions, only: [:create, :destroy]
	get  'signup', to: 'users#new', as: 'signup'
	get  'login',  to: 'sessions#new', as: 'login'
	get  'logout', to: 'sessions#destroy', as: 'logout'
	get  'forgot_password', to: 'sessions#forgot_password', as: 'forgot_password'
	post 'restore_password', to: 'sessions#restore_password', as: 'restore_password'


	# Home and login
	get 'home/index', as: 'home'

	# Root definition
	root 'home#index'
end

app/controllers/system_controls_controller.rb
class SystemControlsController < ApplicationController
	before_action do authorize_manage(:system_controlls) end

	def info
		@company_info = Company.info
	end

	def update_info
		@company_info = Company.info

		@company_info.update(company_info_params)

		render 'info'
	end

	def users
		@user = User.new
		@internal_users = User.where(role: [:admin, :secretary, :executive, :office_chief]).order(:name)
		@external_users = User.where(role: [:tenant, :proprietary]).order(:name)
	end

	def create_user
		@user = User.new(user_params)

		# Validate only these parameters
		validations.each do |param, validator|
			if @user.send(param).send(validator)
				@user.errors.add(param, 'No puede estar vacío')
			end
		end

		if @user.errors.empty? and @user.save(validate: false)
			LogEntry.create user: current_user, datetime: DateTime.now, action: 'creó', model: 'usuario', description: "#{@user.name}"
			redirect_to system_users_path
		else
			@internal_users = User.where(role: [:admin, :secretary, :executive, :office_chief]).order(:name)
			@external_users = User.where(role: [:tenant, :proprietary]).order(:name)
			render 'users'
		end
	end

	def edit_user
		@user = User.find(params[:user_id])
	end

	def update_user
		@user = User.find(params[:user_id])

		if @user.internal? and @user.update(user_params)
			LogEntry.create user: current_user, datetime: DateTime.now, action: 'editó', model: 'usuario', description: "#{@user.name}"
			@users = User.where(role: [:admin, :secretary, :executive, :office_chief]).order(:name)
			render 'update_user'
		elsif not @user.internal? and @user.update(full_user_params)
			LogEntry.create user: current_user, datetime: DateTime.now, action: 'editó', model: 'usuario', description: "#{@user.name}"
			@users = User.where(role: [:tenant, :proprietary]).order(:name)
			render 'update_user'
		else
			render 'edit_user'
		end
	end

	def activate_user
		@user = User.find(params[:user_id])

		@user.update(active: true)
		LogEntry.create user: current_user, datetime: DateTime.now, action: 'activó', model: 'usuario', description: "#{@user.name}"

		if @user.internal?
			@users = User.where(role: [:admin, :secretary, :executive, :office_chief]).order(:name)
		else @user.internal?
			@users = User.where(role: [:tenant, :proprietary]).order(:name)
		end


		render 'update_user'
	end

	def deactivate_user
		@user = User.find(params[:user_id])

		@user.update(active: false)
		LogEntry.create user: current_user, datetime: DateTime.now, action: 'desactivó', model: 'usuario', description: "#{@user.name}"

		if @user.internal?
			@users = User.where(role: [:admin, :secretary, :executive, :office_chief]).order(:name)
		else not @user.internal?
			@users = User.where(role: [:tenant, :proprietary]).order(:name)
		end

		render 'update_user'
	end

	def logs
		@logs = LogEntry.all.order(:datetime)
	end

	private

	def validations
		{:name => :empty?,
		 :rut => :empty?,
		 :role => :nil?,
		 :password => :nil?,
		 :email => :empty?
		}
	end

	def user_params
		params.require(:user).permit(:name, :rut, :role, :password, :email)
	end

	def full_user_params
		params.require(:user)
			.permit(
				:email, :password, :name, :email, :email2,
				:rut, :telephone, :telephone2, :address, :region,
				:commune, :observation, :role,

				representative_attributes: Representative.attribute_names.map(&:to_sym),
				cosigner_attributes:	   User.attribute_names.map(&:to_sym))
	end

	def company_info_params
		params.require(:company)
			.permit(
				:name, :rut, :address, :region, :commune, :email,
				:telephone1, :telephone2, :cellphone, :bank,
				:account_type, :titular, :account_number, :account_email
			)
	end
end

app/views/system_controls/_form.html.erb
<%= simple_form_for @user, url: remote ? system_update_user_path(@user) : system_create_user_path, remote: remote do |f| %>
	<div class="row">
		<div class="col-sm-4"><%= f.input :name, as: :string, label: 'Nombre Completo' %></div>
		<div class="col-sm-4"><%= f.input :rut, as: :string, label: 'Rut', input_html: {class: 'rut-field'} %></div>
		<div class="col-sm-4"><%= f.input :role, collection: User.internal_role_collection, label: 'Perfil', include_blank: false %></div>
	</div>

	<div class="row">
		<div class="col-sm-6"><%= f.input :password, as: :password, label: 'Password' %></div>
		<div class="col-sm-6"><%= f.input :email, as: :string, label: 'Correo Electronico' %></div>
	</div>

	<div class="row">
		<div class="col-sm-8"></div>
		<div class="col-sm-1"><button class="btn btn-danger" data-dismiss="modal">Cancelar</button></div>
		<div class="col-sm-1"></div>
		<div class="col-sm-1"><%= f.submit 'Crear', class: 'btn btn-info' %></div>
		<div class="col-sm-1"></div>
	</div>
<% end %>

app/views/system_controls/_table.html.erb
<div class="table-responsive">
	<table class="table table-bordered table-responsive-sm">
		<thead class="thead-dark">
			<tr class="text-center">
				<th>Nombre</th>
				<th>Email</th>
				<th>Perfil</th>
				<th colspan="2">Acciones</th>
			</tr>
		</thead>
		<tbody>
			<% users.each do |user| %>
				<tr class="text-center">
					<td><%= user.name %></td>
					<td><%= user.email %></td>
					<td><%= user.role_string %></td>
					<td><%= link_to 'Modificar', system_edit_user_path(user), class: 'btn btn-info', remote: true %></td>
					<% if user.active %><td><%= link_to 'Inactivar', system_deactivate_user_path(user), class: 'btn btn-danger', remote: true %></td>
					<% else %>			<td><%= link_to 'Activar', system_activate_user_path(user), class: 'btn btn-success', remote: true %></td><% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/system_controls/_table_logs.html.erb
<table class="table table-bordered table-responsive-sm" id="logs-table">
	<thead class="thead-dark">
		<tr class="text-center">
			<th>Usuario</th>
			<th>Fecha Hora</th>
			<th>Evento</th>
			<th>Descripción</th>
		</tr>
	</thead>
	<tbody>
		<% logs.each do |log_entry| %>
			<tr class="text-center">
				<td><%= log_entry.user.name %></td>
				<td><%= log_entry.datetime.strftime('%d-%m-%Y | %l:%M %p') %></td>
				<td><%= log_entry.action.capitalize %> <%= log_entry.model.capitalize %></td>
				<td><%= log_entry.description %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/system_controls/edit_user.js.erb
modal.reset();
modal.configXl();
modal.setHeader('Editar Usuario');
<% if @user.internal? %>
	modal.setBody("<%= j render 'form', remote: true %>");
<% else %>
	modal.setBody('<%= j render "users/form_#{@user.role}_remote" %>');
<% end %>

helpers.setRutFieldListenerByClass('rut-field');
modal.show();

app/views/system_controls/info.html.erb
<div class="main-content">
	<section class="section">
		<%= render 'partials/title', title: 'Control Sistema' %>

		<div class="section-body">
			<div class="card">

				<div class="card-header d-flex justify-content-between align-items-center">
					<div class="d-flex flex-column align-items-center">
						<h4>Datos de la Empresa</h4>
					</div>
				</div>

				<div class="card-body p-0">
					<%= simple_form_for @company_info, url: system_update_info_path do |f| %>
						<span>Información de la Empresa</span>
						<div class="row row-bordered">
							<div class="col-sm-3">
								<%= f.input :name, label: 'Nombre o Razón Social' %>
							</div>
							<div class="col-sm-2">
								<%= f.input :rut, label: 'Rut', input_html: {class: 'rut-field'} %>
							</div>
							<div class="col-sm-3">
								<%= f.input :address, label: 'Dirección' %>
							</div>
							<div class="col-sm-2">
								<%= f.input :region, label: 'Región', collection: Company.region_collection, include_blank: false, input_html: {onchange: 'helpers.updateCommuneByRegion(event.target.value, "commune-field");', id: 'region-field'} %>
							</div>

							<div class="col-sm-2">
								<%= f.input :commune, label: 'Comuna', collection: Company.commune_collection, include_blank: false, input_html: {id: 'commune-field'} %>
							</div>
						</div>
						<br/>
						<span>Información de Contacto</span>
						<div class="row row-bordered">
							<div class="col-sm-3">
								<%= f.input :email, label: 'Email' %>
							</div>
							<div class="col-sm-3">
								<%= f.input :telephone1, label: 'Teléfono 1' %>
							</div>
							<div class="col-sm-3">
								<%= f.input :telephone2, label: 'Teléfono 2' %>
							</div>
							<div class="col-sm-3">
								<%= f.input :cellphone, label: 'Celular' %>
							</div>
						</div>
						<br/>
						<span>Información Bancaria</span>
						<div class="row row-bordered">
							<div class="col-sm-2">
								<%= f.input :bank, label: 'Nombre del Banco', collection: Company.bank_collection %>
							</div>
							<div class="col-sm-2">
								<%= f.input :account_type, label: 'Tipo Cta', collection: Company.account_type_collection %>
							</div>
							<div class="col-sm-3">
								<%= f.input :titular, label: 'Nombre del Titular' %>
							</div>
							<div class="col-sm-2">
								<%= f.input :account_number, label: 'Número de Cuenta' %>
							</div>
							<div class="col-sm-3">
								<%= f.input :account_email, label: 'Email de Transferencia' %>
							</div>
						</div>
						<br/>

						<%= f.submit 'Actualizar', class: 'btn btn-info float-right' %>
						<button class="btn btn-danger float-right" onclick="event.preventDefault(); window.location.reload();">Cancelar</button>
					<% end %>
				</div>
			</div>
		</div>
	</section>
</div>

<style>
	.row-bordered {
		border-style: solid;
		border-width: 2px;
		border-color: rgba(0, 0, 0, 0.08);
		padding: 5px;
		margin: 0px;
	}

	.float-right {
		float: right;
		margin-right: 10px;
	}
</style>

<% content_for :extra_js do %>
	helpers.setRutFieldListenerByClass('rut-field');
	var currentRegion = document.getElementById('region-field').value;
	helpers.updateCommuneByRegion(currentRegion, 'commune-field');
<% end %>

app/views/system_controls/logs.html.erb
<%= render 'partials/messages' %>

<div class="main-content">
	<section class="section">
		<%= render 'partials/title', title: 'Control Sistema' %>
		<div class="section-body">
			<div class="row">
				<div class="col-12">

					<div class="card">
						<div class="card-header d-flex justify-content-between align-items-center" style="padding: 0;">
							<div class="d-flex flex-column align-items-center">
								<h4>Visor de Eventos</h4>
								<%= render 'partials/excel_button', table_id: 'logs-table', file_name: 'eventosDelSistema' %>
							</div>

							<div class="card-header-form">
								<%= render( 'partials/search_form_with_dates',
											model: 'log_entry',
											init_queries: [],
											constants: {},
											search_vars: [
												'user.name',
												'datetime',
												'action',
												'description',
												],
											time_vars: [
												'datetime',
											],
											table_container_id: 'logs-table-container',
											table_partial: 'system_controls/table_logs',
											query_name: 'logs') %>
							</div>
						</div>

						<div class="card-body p-0">

							<br/>
							<div class="table-responsive" id="logs-table-container">
								<%= render 'system_controls/table_logs', logs: @logs %>
							</div>

						</div>
					</div>

				</div>
			</div>
		</div>
	</section>
</div>

app/views/system_controls/update_user.js.erb
<% if @user.internal? %>
	usersTab = document.getElementById('internal-users');
<% else %>
	usersTab = document.getElementById('external-users');
<% end %>

usersTab.innerHTML = "<%= j render 'table', users: @users %>"

modal.hide()

app/views/system_controls/users.html.erb
<%= render 'partials/messages' %>

<div class="main-content">
	<section class="section">
		<%= render 'partials/title', title: 'Control Sistema' %>
		<div class="section-body">
			<div class="row">
				<div class="col-12">

					<div class="card">
						<div class="card-header d-flex justify-content-between align-items-center">
							<div class="d-flex flex-column align-items-center">
								<h4>Usuarios y Perfiles</h4>
							</div>
						</div>

						<div class="card-body p-0">

							<!-- Tabs -->
							<ul class="nav nav-tabs" role="tablist">
								<li class="nav-item">
									<a class="nav-link active" id="profile-users-tab" data-toggle="tab" href="#profile-users" role="tab"  aria-selected="true">Usuario y Perfil</a>
								</li>

								<li class="nav-item">
									<a class="nav-link" id="internal-users-tab" data-toggle="tab" href="#internal-users" role="tab" aria-selected="false">Usuarios Internos</a>
								</li>

								<li class="nav-item">
									<a class="nav-link" id="external-users-tab" data-toggle="tab" href="#external-users" role="tab"  aria-selected="false">Usuarios Externos</a>
								</li>
							</ul>

							<div class="tab-content tab-bordered">

								<!-- Basic information tab -->
								<div class="tab-pane fade show active min-height-500px " id="profile-users" role="tabpanel" aria-labelledby="profile-users-tab">
									<%= render 'form', remote: false %>
								</div>

								<div class="tab-pane fade min-height-500px " id="internal-users" role="tabpanel" aria-labelledby="internal-users-tab">

									<%= render 'table', users: @internal_users %>

								</div>

								<div class="tab-pane fade min-height-500px " id="external-users" role="tabpanel" aria-labelledby="external-users-tab">

									<%= render 'table', users: @external_users %>

								</div>
							</div>

						</div>
					</div>

				</div>
			</div>
		</div>
	</section>
</div>

<% content_for :extra_js do %>
	helpers.setRutFieldListenerByClass('rut-field');
<% end %>